name: CI
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    name: â¬£ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Install dependencies
        run: npm install

      - name: â–¶ï¸ Run format:check script
        run: npm run format:check

      - name: â–¶ï¸ Run lint script
        run: npm run lint

  test:
    name: ğŸ§ª Test (Node@${{ matrix.node }} - ESLint@${{ matrix.eslint }} - ${{
      matrix.os }})
    strategy:
      matrix:
        eslint: [7]
        node: [10, 12.0.0, 12, 14.0.0, 14, 16, 18] # 10.0.0 is missing
        os: [ubuntu-latest]
        include:
          # On other platforms
          - os: windows-latest
            eslint: 7
            node: 18
          - os: macos-latest
            eslint: 7
            node: 18
          # On old ESLint versions
          - eslint: 6
            node: 18
            os: ubuntu-latest
          # - eslint: 5
          #   node: 18
          #   os: ubuntu-latest
          # On the minimum supported ESLint/Node.js version
          # - eslint: 5.0.0
          #   node: 10.0.0
          #   os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: ğŸ“¥ Install dependencies
        run: npm install

      - name: ğŸ“¥ Install ESLint v${{ matrix.eslint }}
        run: npm install --save-dev eslint@${{ matrix.eslint }}

      - name: ğŸ— Build
        run: npm run build

      - name: â–¶ï¸ Run test script
        run: npm run test

      - name: â¬†ï¸ Upload coverage report
        uses: codecov/codecov-action@v3
